---
- name: Install Common Dev Tools
  apt: name={{ item }} state=present update_cache=yes  cache_valid_time=86400
  become: yes
  with_items:
    - git
    - vim
    - beanstalkd
    - supervisor
    - sed
    - node-gyp
    - node-bindings
  notify:
    # - Restart Beanstalk
    - Restart Supervisor

- name: Configure Vim
  copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: 0644
  become: yes
